config/routes.rb
Rails.application.routes.draw do

  # root to: "posts#index"

  get 'posts' => 'posts#index'

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :posts do
    resources :comments, :likes
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :post
  belongs_to :user

end

app/models/like.rb
class Like < ActiveRecord::Base

  belongs_to :post
  
end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_attached_file :image, :styles => { :medium => "600x550>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates_attachment :image, presence: true
  validates :title, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :username, presence: true

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "50x50>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates_attachment :image, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
require 'time_ago_in_words'

class ApplicationController < ActionController::Base

  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  protected

  def configure_devise_permitted_parameters
    registration_params = [:username, :email, :image, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) {
        |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) {
        |u| u.permit(registration_params)
      }
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    @comment.save
    redirect_to posts_path
  end

  def comment_params
    params.require(:comment).permit(:thoughts)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    render 'index'
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @post.likes.create
    render json: {new_like_count: @post.likes.count}
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, :except => [:index]

  def index
    @posts = Post.all
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.time = Time.now
    @post.save ? (redirect_to posts_path) : (render 'new')
  end

  def post_params
    params.require(:post).permit(:image, :title)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<p>
  Home Page
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <title>Instagram Clone</title>
    <%= stylesheet_link_tag    'main', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="wrapper">
      <header>
        <div class="custom-navbar">
          <% if user_signed_in? %>
            <%= link_to "New Post", new_post_path, class: 'new-post-link' %>
            <a class="header-instagram-logo" href="/">Instagram</a>
            <p class="current-username"><%= current_user.username %> | <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'sign-out-link' %></p>
          <% else %>
            <%= link_to "Login", new_user_session_path %> |
            <%= link_to "Sign up", new_user_registration_path %>
          <% end %>
        </div>
      </header>
      <main>
        <!-- <%= notice %> -->
        <!-- <%= alert %> -->
        <%= yield %>
      </main>
      <footer>
        © 2016 Instagram Clone by Hamza Sheikh, while at <a href="http://www.makersacademy.com/" target="_blank">Makers Academy</a> | <a href="https://github.com/hsheikhm" target="_blank">GitHub</a> | <a href="https://uk.linkedin.com/in/hamza-sheikh-b111a975" target="_blank">LinkedIn</a> | <a href="https://hsheikhm.wordpress.com/" target="_blank">Blog</a> |
      </footer>
    </div>
    <script type="text/javascript">
      $('main').hide().fadeIn(1000);
    </script>
  </body>
</html>

app/views/posts/index.html.erb
<section class="posts-section">
  <div class="posts-div">
    <% if @posts.any? %>
      <% @posts.reverse.each do |post| %>
      <article class="each-post">
        <header class="post-header">
          <%= image_tag post.user.image.url(:thumb), class: 'post-user-image' %>
          <div class="post-user-username">
            <%= post.user.username %>
          </div>
          <div class="post-timestamp">
            <%= time_ago_in_words(post.time) + ' ago' %>
          </div>
        </header>
        <div class="post-image-div">
          <%= image_tag post.image.url(:medium), class: 'post-image' %>
        </div>
        <div class="post-extra-section">
          <span class="likes_count"> <%= post.likes.count %> </span> <span class="likes-word"><%= 'like'.pluralize(post.likes.count) %></span>
          <ul class="post-details">
            <li class="post-user-and-title">
              <span class="post-detail-user-username"><%= post.user.username %></span>
              <span><strong><%= post.title %></strong></span>
            </li>
            <% if post.comments.any? %>
              <% post.comments.each do |comment| %>
            <li class="post-comment">
              <span class="comment-user-username"><%= comment.user.username %></span>
              <span class="comment-user-thoughts"><%= comment.thoughts %></span>
            </li>
                <% end %>
            <% else %>
              <p>No comments.</p>
            <% end %>
          </ul>
          <section class="add-comment-section">
          </section>
          <%= link_to post_likes_path(post), class: 'likes-link' do %>
          <% end %>
          <div class="new-comment-form">
            <%= form_for [post, @comment] do |f| %>
            <%= f.text_area :thoughts, placeholder: "Add a comment...", id: 'new-comment-text' %>
            <%= f.submit "Submit", class: 'submit-comment-button' %>
            <% end %>
          </div>
        </div>
      </article>
      <% end %>
    <% end %>
  </div>
</section>

app/views/posts/new.html.erb
 <% if @post.errors.any? %>
   <section id="errors" >
     <h3> <%= pluralize(@post.errors.count, "error") %> prohibited this post from being submitted: </h2>
     <ul>
       <% @post.errors.full_messages.each do |message| %>
         <li><%= message %></li>
       <% end %>
     </ul>
   </section>
 <% end %>

<section class="new-post-section">
  <div class="new-post-file">
    <%= form_for @post, url: posts_path, html: {multipart: true} do |f| %>
      <%= f.label "Select Image", class: "select-image-label" %>
      <%= f.file_field :image, onchange: "previewImage(event)", id: "new-image" %>
      <%= f.text_field :title, placeholder: "Give your post a title...", id: 'new-post-title-text' %>
      <%= f.submit "Post Image", class: "new-post-submit-button" %>
      <% end %>
  </div>
  <div class="new-post-image-div">
    <img id="image-preview"/>
  </div>
  <script>
    var previewImage = function(event) {
      var output = document.getElementById('image-preview');
      output.src = URL.createObjectURL(event.target.files[0]);
    };
  </script>
</section>